"""Constants for the shapes module"""

from astrohud.lib.ephemeris.enums import Sign


IMG_SIZE_SMALL = 100
IMG_SIZE_BIG = 150


MINOR_SIGN_LABELS = {
    Sign.ANDROMEDA: 'And',
    Sign.ANTLIA: 'Ant',
    Sign.APUS: 'Aps',
    Sign.AQUARIUS: 'Aqr',
    Sign.AQUILA: 'Aql',
    Sign.ARA: 'Ara',
    Sign.ARIES: 'Ari',
    Sign.AURIGA: 'Aur',
    Sign.BOOTES: 'Boo',
    Sign.CAELUM: 'Cae',
    Sign.CAMELOPARDALIS: 'Cam',
    Sign.CANCER: 'Cnc',
    Sign.CANES_VENATICI: 'CVn',
    Sign.CANIS_MAJOR: 'CMa',
    Sign.CANIS_MINOR: 'CMi',
    Sign.CAPRICORN: 'Cap',
    Sign.CARINA: 'Car',
    Sign.CASSIOPEIA: 'Cas',
    Sign.CENTAURUS: 'Cen',
    Sign.CEPHEUS: 'Cep',
    Sign.CETUS: 'Cet',
    Sign.CHAMAELEON: 'Cha',
    Sign.CIRCINUS: 'Cir',
    Sign.COLUMBA: 'Col',
    Sign.COMA_BERENICES: 'Com',
    Sign.CORONA_AUSTRALIS: 'CrA',
    Sign.CORONA_BOREALIS: 'CrB',
    Sign.CORVUS: 'Crv',
    Sign.CRATER: 'Crt',
    Sign.CRUX: 'Cru',
    Sign.CYGNUS: 'Cyg',
    Sign.DELPHINUS: 'Del',
    Sign.DORADO: 'Dor',
    Sign.DRACO: 'Dra',
    Sign.EQUULEUS: 'Equ',
    Sign.ERIDANUS: 'Eri',
    Sign.FORNAX: 'For',
    Sign.GEMINI: 'Gem',
    Sign.GRUS: 'Gru',
    Sign.HERCULES: 'Her',
    Sign.HOROLOGIUM: 'Hor',
    Sign.HYDRA: 'Hya',
    Sign.HYDRUS: 'Hyi',
    Sign.INDUS: 'Ind',
    Sign.LACERTA: 'Lac',
    Sign.LEO: 'Leo',
    Sign.LEO_MINOR: 'LMi',
    Sign.LEPUS: 'Lep',
    Sign.LIBRA: 'Lib',
    Sign.LUPUS: 'Lup',
    Sign.LYNX: 'Lyn',
    Sign.LYRA: 'Lyr',
    Sign.MENSA: 'Men',
    Sign.MICROSCOPIUM: 'Mic',
    Sign.MONOCEROS: 'Mon',
    Sign.MUSCA: 'Mus',
    Sign.NORMA: 'Nor',
    Sign.OCTANS: 'Oct',
    Sign.OPHIUCHUS: 'Oph',
    Sign.ORION: 'Ori',
    Sign.PAVO: 'Pav',
    Sign.PEGASUS: 'Peg',
    Sign.PERSEUS: 'Per',
    Sign.PHOENIX: 'Phe',
    Sign.PICTOR: 'Pic',
    Sign.PISCES: 'Psc',
    Sign.PISCIS_AUSTRINUS: 'PsA',
    Sign.PUPPIS: 'Pup',
    Sign.PYXIS: 'Pyx',
    Sign.RETICULUM: 'Ret',
    Sign.SAGITTA: 'Sge',
    Sign.SAGITTARIUS: 'Sgr',
    Sign.SCORPIO: 'Sco',
    Sign.SCULPTOR: 'Scl',
    Sign.SCUTUM: 'Sct',
    Sign.SERPENS_CAPUT: 'Ser',
    Sign.SERPENS_CAUDA: 'Ser',
    Sign.SEXTANS: 'Sex',
    Sign.TAURUS: 'Tau',
    Sign.TELESCOPIUM: 'Tel',
    Sign.TRIANGULUM: 'Tri',
    Sign.TRIANGULUM_AUSTRALE: 'TrA',
    Sign.TUCANA: 'Tuc',
    Sign.URSA_MAJOR: 'UMa',
    Sign.URSA_MINOR: 'UMi',
    Sign.VELA: 'Vel',
    Sign.VIRGO: 'Vir',
    Sign.VOLANS: 'Vol',
    Sign.VULPECULA: 'Vul',
}